# Generated by Django 5.0.1 on 2024-03-22 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=32, verbose_name='管理员用户名')),
                ('admin_password', models.CharField(max_length=64, verbose_name='管理员密码')),
            ],
        ),
    ]
