# Generated by Django 5.0.1 on 2024-04-03 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0003_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=64, verbose_name='订单号')),
                ('product_name', models.CharField(max_length=32, verbose_name='商品名称')),
                ('order_price', models.IntegerField(verbose_name='订单价格')),
                ('order_status', models.IntegerField(choices=[(1, '待支付'), (2, '已支付')], default=1, verbose_name='订单价格')),
                ('order_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_web.admin', verbose_name='订单创建者')),
            ],
        ),
    ]
