# Generated by Django 5.0.1 on 2024-04-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0004_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boss_name', models.CharField(max_length=32, verbose_name='姓名')),
                ('boss_age', models.IntegerField(verbose_name='年龄')),
                ('boss_image', models.CharField(max_length=128, verbose_name='头像')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(choices=[(1, '待支付'), (2, '已支付')], default=1, verbose_name='订单状态'),
        ),
    ]
