# Generated by Django 5.0.1 on 2024-04-10 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0005_boss_alter_order_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=32, verbose_name='城市名称')),
                ('city_population', models.IntegerField(verbose_name='城市人口数')),
                ('city_logo', models.FileField(max_length=128, upload_to='city/', verbose_name='城市Logo')),
            ],
        ),
    ]
