# Generated by Django 5.0.1 on 2024-04-15 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0007_branchperformance_employeeperformance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='title',
            field=models.CharField(max_length=64, verbose_name='部门名称'),
        ),
    ]
